### ISSUE TITLE
Tom's problem

### ISSUE THREAD

**Issue by romeokienzler** [IBM/coursera#1]
https://www.coursera.org/learn/ds/discussions/all/threads/h207-6B5Eeiz4w5JxTItyg

**Comment by Husnain08** [comment]
![capture](https://user-images.githubusercontent.com/38109416/45306057-1e3cdf00-b535-11e8-8fdd-67b3346e8411.JPG)

The given error is "ValueError: Arguments 'xs' and 'ys' must be of same size."
Now , the error is caused by incorrect slicing of the array that is being passed into the "scatter" function. 
Since it seems that you want to plot a scatter of one of the column of data-frame against the other,, you should create result_array_hardness and result_array_temperature such that 
result_array_hardness=df[:,0]
result_array_temperature=df[:,1]
